################################################################################
### Part 0.1) Downloading part
################################################################################

rule download_genomes:
    output:
        "../data/genomes/{species}_genomes.fna"
    shell:
        "bash ../scripts/download_genomes.sh {wildcards.species} {output}"

rule download_features:
    output:
        "../data/factors/features/{species}_feature_table.txt"
    shell:
        "bash ../scripts/download_features.sh {wildcards.species} {output}"

rule download_genes:
    output:
        "../data/factors/genes/{species}_genes.gff"
    shell:
        "bash ../scripts/download_genes.sh {wildcards.species} {output}"

rule download_repeats:
    output:
        "../data/factors/repeats/{species}_repeats.txt"
    shell:
        "bash ../scripts/download_repeats.sh {wildcards.species} {output}"

rule download_rr:
    output:
        "../data/factors/recombination_rates/{species}_RR_spline.RData"
    shell:
        "bash ../scripts/download_repeats.sh {wildcards.species} {output}"

################################################################################
### Part 0.2) Extract and clean ranges
################################################################################

rule factor_proxies:
    input:
        "../data/genomes/{species}_genomes.fna",
        "../data/factors/repeats/{species}_repeats.txt",
        "../data/factors/features/{species}_feature_table.txt",
        "../data/factors/genes/{species}_genes.gff"
    output:
        "../data/following/factor_proxies/{species}/{factors}_proxies_done.txt"
    shell:
        "python3 ../scripts/factor_proxies.py {wildcards.factors} {input} \
        {output}"

rule extract_overlaps:
    input:
        "../data/genomes/{species}_genomes.fna"
    output:
        "../data/following/factor_proxies/overlaps/{species}_done.txt"
    threads:
        99
    shell:
        "python3 ../scripts/extract_overlaps.py {input} {threads} {output}"

rule clean_ranges:
    input:
        "../data/genomes/{species}_genomes.fna",
        "../data/following/factor_proxies/overlaps/{species}_done.txt"
    output:
        "../data/following/factor_proxies/cleaning/{species}_done.txt"
    threads:
        99
    shell:
        "python3 ../scripts/removing_overlaps.py {input} {threads} {output}"

rule extract_uncategorized:
    input:
        "../data/genomes/{species}_genomes.fna",
        "../data/following/factor_proxies/cleaning/{species}_done.txt"
    output:
        "../data/following/factor_proxies/uncategorized/{species}_done.txt"
    threads:
        99
    shell:
        "python3 ../scripts/extract_uncategorized.py {input} {threads} {output}"

rule factor_percentages:
    input:
        "../data/genomes/{species}_genomes.fna",
        "../data/following/factor_proxies/uncategorized/{species}_done.txt"
    output:
        "../files/factor_percentages/{windows}/{species}.txt"
    threads:
        99
    shell:
        "python3 ../scripts/factor_percentages.py {input} {wildcards.windows} \
        {output}"

rule filter_factors:
    input:
        "../files/factor_percentages/{windows}/{species}.txt"
    output:
        "../data/following/factor_filtered/{windows}/{species}_done.txt"
    threads:
        99
    shell:
        "python3 ../scripts/filter_by_percentages.py {input} \
        {wildcards.species} {output}"

################################################################################
### Part A)
################################################################################

rule extract_overlaps:
    output:
        "files/overlaps/{windows}/overlap_percentages.txt"
    threads:
        99
    shell:
        "python3 scripts/extract_overlap_factors.py {wildcards.windows} \
        {threads} {output}"

rule barplot_overlap:
    input:
        "files/overlaps/{windows}/overlap_percentages.txt"
    output:
        "files/results/{windows}/overlap_all_species.png"
    shell:
        "Rscript scripts/barplots_factors_overlaps.R {input} {output}"

rule extract_percentages:
    output:
        "files/overlaps/{windows}/factor_percentages.txt"
    threads:
        99
    shell:
        "python3 scripts/extract_overall_factors_percentages.py \
        {wildcards.windows} {output}"

rule barplot_percentages:
    input:
        "files/overlaps/{windows}/factor_percentages.txt"
    output:
        "files/results/{windows}/percentages_all_species.png"
    shell:
        "Rscript scripts/barplots_factors_percentages.R {input} {output}"
