rule download_genomes:
    output:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna"
    shell:
        "bash ../scripts/download_genomes.sh {wildcards.species} {output}"

rule download_features:
    output:
        "../data/factors/features/{species}_feature_table.txt"
    shell:
        "bash ../scripts/download_features.sh {wildcards.species} {output}"

rule download_repeats:
    output:
        "../data/factors/repeats/{species}_repeats.txt"
    shell:
        "bash ../scripts/download_repeats.sh {wildcards.species} {output}"

rule download_rr:
    output:
        "../data/factors/recombination_rates/{species}_RR_spline.RData"
    shell:
        "bash ../scripts/download_repeats.sh {wildcards.species} {output}"

rule sampling:
    input:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna"
    output:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna"
    shell:
        "python3 ../scripts/sampling_windows.py {input} {wildcards.n_samples} \
            {wildcards.windows} {output}"

rule CGR:
    input:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna"
    output:
        "../data/following/CGRs/{windows}_{n_samples}/{species}_done.txt"
    threads:
        99
    shell:
        "python3 ../scripts/windowed_CGR.py {input} {wildcards.windows} \
            {threads} {output}"

rule CDS_extract:
    input:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna",
        "../data/factors/features/{species}_feature_table.txt",
    output:
        "../files/factors/{windows}_{n_samples}/{species}_CDS.txt"
    shell:
        "python3 ../scripts/extract_feature.py {input} {wildcards.windows} \
            CDS {output}"

rule intron_extract:
    input:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna",
        "../data/factors/features/{species}_feature_table.txt",
    output:
        "../files/factors/{windows}_{n_samples}/{species}_intron.txt"
    shell:
        "python3 ../scripts/extract_feature.py {input} {wildcards.windows} \
            intron {output}"

rule UTR_extract:
    input:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna",
        "../data/factors/features/{species}_feature_table.txt",
    output:
        "../files/factors/{windows}_{n_samples}/{species}_UTR.txt"
    shell:
        "python3 ../scripts/extract_feature.py {input} {wildcards.windows} \
            UTR {output}"

rule RNA_extract:
    input:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna",
        "../data/factors/features/{species}_feature_table.txt",
    output:
        "../files/factors/{windows}_{n_samples}/{species}_RNA.txt"
    shell:
        "python3 ../scripts/extract_feature.py {input} {wildcards.windows} \
            RNA {output}"

rule LCR_extract:
    input:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna",
        "../data/factors/repeats/{species}_repeats.txt",
    output:
        "../files/factors/{windows}_{n_samples}/{species}_LCR.txt"
    shell:
        "python3 ../scripts/extract_repeats.py {input} {wildcards.windows} \
            LCR {output}"

rule TE_extract:
    input:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna",
        "../data/factors/repeats/{species}_repeats.txt",
    output:
        "../files/factors/{windows}_{n_samples}/{species}_TE.txt"
    shell:
        "python3 ../scripts/extract_repeats.py {input} {wildcards.windows} \
            TE {output}"

rule tandem_extract:
    input:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna",
        "../data/factors/repeats/{species}_repeats.txt",
    output:
        "../files/factors/{windows}_{n_samples}/{species}_tandem.txt"
    shell:
        "python3 ../scripts/extract_repeats.py {input} {wildcards.windows} \
            tandem {output}"
rule RR_extract:
    input:
        "../data/samples/{windows}_{n_samples}/{species}_sample.fna",
        "../data/factors/recombination_rates/{species}_RR_spline.RData",
    output:
        "../files/factors/{windows}_{n_samples}/{species}_RR.txt"
    shell:
        "python3 ../scripts/extract_RR.py {input} {wildcards.windows} \
            {output}"

rule ratio_extract:
    input:
        "../data/following/CGRs/{windows}_{n_samples}/{species}_done.txt"
    output:
        "../files/factors/{windows}_ratios/{species}.txt"
    shell:
        "python3 ../scripts/extract_nucleotide_ratio.py {input} \
            {wildcards.species} {wildcards.windows} {threads} {output}"

rule FCGR:
    input:
        "../data/following/CGRs/{windows}_{n_samples}/{species}_done.txt"
    output:
        "files/FCGRs/{windows}_{n_samples}_{kmer}/{species}_FCGRs.txt"
    threads:
        99
    shell:
        "python3 ../scripts/windowed_FCGR.py {input} {wildcards.species} \
            {wildcards.windows} {wildcards.kmer} {threads} {output}"

rule FCGR_dist:
    input:
        "files/FCGRs/{windows}_{n_samples}_{kmer}/{species}_FCGRs.txt"
    output:
        "files/distances/pearson/{windows}_{n_samples}_{kmer}/{species}_dist_matrix.RData"
    threads:
        99
    shell:
        "Rscript ../scripts/pearson_distance.R {input} {output}"

rule fitting:
    input:
        "files/distances/pearson/{windows}_{n_samples}_{kmer}/{species}_dist_matrix.RData"
    output:
        "files/distances/pearson/{windows}_{n_samples}_{kmer}/{species}_fit.RData"
    threads:
        99
    shell:
        "Rscript ../scripts/fitting_dist.R {input} {output}"

rule correlation:
    input:
        "files/distances/pearson/{windows}_{n_samples}_{kmer}/{species}_dist_matrix.RData",
        "../files/factors/{windows}_{n_samples}/{species}_{factors}.txt"
    output:
        "files/results/{windows}_{n_samples}_{kmer}_{factors}/{species}_correlation.png"
    shell:
        "Rscript ../scripts/cor_dist_factor.R {output} {input} FCGRs \
            {wildcards.factors} {wildcards.windows} {wildcards.kmer}"

rule MDS:
    input:
        "files/distances/pearson/{windows}_{n_samples}_{kmer}/{species}_fit.RData",
        "../files/factors/{windows}_{n_samples}/{species}_{factors}.txt"
    output:
        "files/results/{windows}_{n_samples}_{kmer}_{factors}/{species}_MDS.png"
    shell:
        "Rscript ../scripts/MDS_dist_factor.R {output} {input} FCGRs \
            {wildcards.factors} {wildcards.windows} {wildcards.kmer}"

rule ratio_figure:
    input:
        "files/distances/pearson/{windows}_{n_samples}_{kmer}/{species}_dist_matrix.RData",
        "../files/factors/{windows}_ratios/{species}.txt"
    output:
        "files/results/{windows}_{n_samples}_{kmer}_ratios/{species}.png"
    shell:
        "Rscript ../scripts/nucleotide_ratio_figures.R {output} {input} \
            {wildcards.windows} FCGRs {wildcards.kmer}"

rule linear_model:
    input:
        "files/distances/pearson/{windows}_{n_samples}_{kmer}/{species}_fit.RData",
        "../files/factors/{windows}_{n_samples}/{species}_RR.txt",
        "../files/factors/{windows}_{n_samples}/{species}_LCR.txt",
        "../files/factors/{windows}_{n_samples}/{species}_CDS.txt"
    output:
        "files/results/{windows}_{n_samples}_{kmer}_LM/{species}_model.txt",
        "files/results/{windows}_{n_samples}_{kmer}_LM/{species}_plot.png"

    shell:
        "Rscript ../scripts/MDS_dist_factor.R {output} {input} FCGRs \
            {wildcards.factors} {wildcards.windows} {wildcards.kmer}"
