rule purifying:
    input:
        "../data/genomes/{species}_genomes.fna",
        "../data/factors/repeats/{species}_repeats.txt",
        "../data/factors/features/{species}_feature_table.txt"
    output:
        "data/genomes/{windows}/{species}_{factors}_pure.fna"
    shell:
        "python3 scripts/masking_to_pure.py {wildcards.factors} \
            {wildcards.windows} {input} {output}"

rule CGR:
    input:
        "data/genomes/{windows}/{species}_{factors}_pure.fna"
    output:
        "data/following/CGRs/{windows}/{species}_{factors}_done.txt"
    threads:
        99
    shell:
        "python3 ../scripts/windowed_CGR.py {input} {wildcards.windows} \
            {threads} {output} {wildcards.factors}"

rule FCGR:
    input:
        "data/following/CGRs/{windows}/{species}_{factors}_done.txt"
    output:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_FCGRs.txt"
    threads:
        99
    shell:
        "python3 ../scripts/windowed_FCGR.py {input} {wildcards.species} \
            {wildcards.windows} {wildcards.kmer} {threads} {output} \
            {wildcards.factors}"

rule FCGR_dist:
    input:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_FCGRs.txt"
    output:
        "files/distances/pearson/{windows}_{kmer}/{species}_{factors}_dist_matrix.RData"
    threads:
        99
    shell:
        "Rscript ../scripts/pearson_distance.R {input} {output} {wildcards.factors}"


rule boxplots:
    input:
        "files/distances/pearson/{windows}_{kmer}/{species}_dist_matrix.RData",
        "../files/factors/{windows}/{species}_{factors}.txt"
    output:
        "files/results/{windows}_{kmer}_{factors}/{species}_correlation.png"
    shell:
        "Rscript ../scripts/cor_dist_factor.R {output} {input} FCGRs \
            {wildcards.factors} {wildcards.windows} {wildcards.kmer}"
