rule CGR:
    input:
        "../data/genomes/{species}_genomes.fna"
    output:
        "../data/following/CGRs/{windows}/{species}_done.txt"
    threads:
        99
    shell:
        "python3 ../scripts/windowed_CGR.py {input} {wildcards.windows} \
            {threads} {output}"

rule feature_extract:
    input:
        "../data/genomes/{species}_genomes.fna",
        "../data/genomes/{species}_feature_table.txt",
        "../data/genomes/{species}_repeats.txt"
    output:
        "../files/features/{windows}_{features}/{species}.txt"
    shell:
        "python3 ../scripts/extract_feature.py {wildcards.windows} \
            {wildcards.features} {output} {input}"

rule ratio_extract:
    input:
        "../data/following/CGRs/{windows}/{species}_done.txt"
    output:
        "../files/features/{windows}_ratios/{species}.txt"
    shell:
        "python3 ../scripts/nucleotide_ratio_figures.R {input} \
            {wildcards.species} {wildcards.windows} {threads} {output}"

rule DFT:
    input:
        "../data/following/CGRs/{windows}/{species}_done.txt"
    output:
        "files/DFTs/{windows}/{species}_DFTs.txt"
    threads:
        99
    shell:
        "python3 scripts/windowed_DFT.py {input} {wildcards.species} \
            {wildcards.windows} {threads} {output}"

rule DFT_dist:
    input:
        "files/DFTs/{windows}/{species}_DFTs.txt",
    output:
        "files/distances/euclidean/{windows}/{species}_dist_matrix.txt"
    threads:
        99
    shell:
        "Rscript scripts/euclidean_distance.R {input} {output}"

rule figures:
    input:
        "files/distances/euclidean/{windows}/{species}_dist_matrix.txt",
        "../files/features/{windows}_{features}/{species}.txt"
    output:
        "files/results/{windows}_{features}/{species}_correlation.png",
        "files/results/{windows}_{features}/{species}_MDS.png"
    shell:
        """
        Rscript ../scripts/cor_dist_feature.R {output} {input} DFTs \
            {wildcards.features} {wildcards.windows}
        Rscript ../scripts/MDS_dist_feature.R {output} {input} DFTs \
            {wildcards.features} {wildcards.windows}
        """
