GS, = glob_wildcards("config/gs/{any}")

rule CGR:
    input:
        "../data/genomes/{species}_genomes.fna"
    output:
        "../data/following/CGRs/{windows}/{species}_done.txt"
    threads:
        3
    shell:
        "python3 ../scripts/windowed_CGR.py {input} {wildcards.windows} \
        {threads} {output}"

rule feature_extract:
    input:
        "../data/genomes/{species}_genomes.fna",
        "../data/genomes/{species}_feature_table.txt",
        "../data/genomes/{species}_repeats.txt"
    output:
        "../files/features/{windows}_{features}/{species}.txt"
    shell:
        "python3 ../scripts/extract_feature.py {wildcards.windows} \
            {wildcards.features} {output} {input}"

rule DFT:
    input:
        "../data/following/CGRs/{windows}/{species}_done.txt",
        "../data/genomes/{species}_genomes.fna"
    output:
        "files/DFTs/{windows}/{species}_DFTs.txt"
    threads:
        3
    shell:
        "python3 scripts/windowed_DFT.py {input} {wildcards.windows} {threads} {output}"

rule DFT_dist:
    input:
        "files/DFTs/{windows}/{species}_DFTs.txt",
        "../data/genomes/{species}_genomes.fna",
    output:
        "files/distances/euclidean/{windows}/{species}_dist_matrix.txt"
    shell:
        "python3 scripts/euclidean_dist.py {input} {wildcards.windows} {output}"

rule figures:
    input:
        "files/distances/euclidean/{windows}/{species}_dist_matrix.txt",
        "../files/features/{windows}_{features}/{species}.txt",
        expand("config/gs/{gs}", gs = GS)
    output:
        "files/results/{windows}_{features}/{species}_correlation.png",
        "files/results/{windows}_{features}/{species}_MDS.png"
    shell:
        """
        Rscript ../scripts/cor_dist_feature.R {output} {input} \
            {wildcards.features} {wildcards.windows}
        Rscript ../scripts/MDS_dist_feature.R {output} {input} \
            {wildcards.features} {wildcards.windows}
        """
