ruleorder: finding_center > masked_FCGR

rule download_genomes:
    output:
        "../data/genomes/{species}_genomes.fna"
    shell:
        "bash ../scripts/download_genomes.sh {wildcards.species} {output}"

rule download_features:
    output:
        "../data/factors/features/{species}_feature_table.txt"
    shell:
        "bash ../scripts/download_features.sh {wildcards.species} {output}"

rule download_repeats:
    output:
        "../data/factors/repeats/{species}_repeats.txt"
    shell:
        "bash ../scripts/download_repeats.sh {wildcards.species} {output}"

rule download_rr:
    output:
        "../data/factors/recombination_rates/{species}_RR_spline.RData"
    shell:
        "bash ../scripts/download_repeats.sh {wildcards.species} {output}"

rule finding_center:
    input:
        "../scaling/files/FCGRs/{windows}_{kmer}/{species}_FCGRs.txt",
        "../scaling/files/distances/pearson/{windows}_{kmer}/{species}_dist_matrix.RData"
    output:
        "files/FCGRs/{windows}_{kmer}/{species}_center_FCGRs.txt"
    shell:
        "python3 scripts/get_center_FCGRs.py {input} {output}"

rule masking:
    input:
        "../data/genomes/{species}_genomes.fna",
        "../data/factors/repeats/{species}_repeats.txt",
        "../data/factors/features/{species}_feature_table.txt"
    output:
        "data/genomes/{windows}/{species}_{factors}_masked.fna"
    shell:
        "python3 scripts/masking_to_no_factor.py {wildcards.factors} \
            {wildcards.windows} {input} {output}"

rule masked_CGR:
    input:
        "data/genomes/{windows}/{species}_{factors}_masked.fna"
    output:
        "data/following/CGRs/{windows}/{species}_{factors}_masked_done.txt"
    threads:
        99
    shell:
        "python3 ../scripts/windowed_CGR.py {input} {wildcards.windows} \
            {threads} {output} {wildcards.factors}"

rule masked_FCGR:
    input:
        "data/following/CGRs/{windows}/{species}_{factors}_masked_done.txt"
    output:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_masked_FCGRs.txt"
    threads:
        99
    shell:
        "python3 ../scripts/windowed_FCGR.py {input} {wildcards.species} \
            {wildcards.windows} {wildcards.kmer} {threads} {output} \
            {wildcards.factors}"

rule masked_concatenating:
    input:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_masked_FCGRs.txt",
        "files/FCGRs/{windows}_{kmer}/{species}_center_FCGRs.txt"
    output:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_masked_vs_center_FCGRs.txt"
    shell:
        "cat {input} >> {output}"

rule masked_FCGRs_dist:
    input:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_masked_vs_center_FCGRs.txt"
    output:
        "files/distances/pearson/{windows}_{kmer}/{species}_{factors}_masked_vs_center_dist_matrix.RData"
    threads:
        99
    shell:
        "Rscript ../scripts/pearson_distance.R {input} {output}"

rule pure_concatenating:
    input:
        "../purifying/files/FCGRs/{windows}_{kmer}/{species}_{factors}_pure_FCGRs.txt",
        "files/FCGRs/{windows}_{kmer}/{species}_center_FCGRs.txt"
    output:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_pure_vs_center_FCGRs.txt"
    shell:
        "cat {input} >> {output}"

rule pure_FCGRs_dist:
    input:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_pure_vs_center_FCGRs.txt"
    output:
        "files/distances/pearson/{windows}_{kmer}/{species}_{factors}_pure_vs_center_dist_matrix.RData"
    threads:
        99
    shell:
        "Rscript ../scripts/pearson_distance.R {input} {output}"

rule whole_concatenating:
    input:
        "../scaling/files/FCGRs/{windows}_{kmer}/{species}_FCGRs.txt",
        "files/FCGRs/{windows}_{kmer}/{species}_center_FCGRs.txt"
    output:
        "files/FCGRs/{windows}_{kmer}/{species}_whole_vs_center_FCGRs.txt"
    shell:
        "cat {input} >> {output}"

rule whole_FCGRs_dist:
    input:
        "files/FCGRs/{windows}_{kmer}/{species}_whole_vs_center_FCGRs.txt"
    output:
        "files/distances/pearson/{windows}_{kmer}/{species}_whole_vs_center_dist_matrix.RData"
    threads:
        99
    shell:
        "Rscript ../scripts/pearson_distance.R {input} {output}"

rule boxplots:
    output:
        "files/results/{windows}_{kmer}/{species}_boxplots_all_factors.png"
    shell:
        "Rscript scripts/boxplots_factor_center.R {output} {wildcards.windows}\
            {wildcards.kmer} {wildcards.species}"
