ruleorder: finding_center > FCGR

rule finding_center:
    input:
        "../scaling/files/FCGRs/{windows}_{kmer}/{species}_FCGRs.txt",
        "../scaling/files/distances/pearson/{windows}_{kmer}/{species}_dist_matrix.RData"
    output:
        "files/FCGRs/{windows}_{kmer}/{species}_center_FCGRs.txt"
    shell:
        "python3 scripts/get_center_FCGRs.py {input} {output}"

rule masking:
    input:
        "../data/genomes/{species}_genomes.fna",
        "../data/factors/repeats/{species}_repeats.txt",
        "../data/factors/features/{species}_feature_table.txt"
    output:
        "data/genomes/{windows}/{species}_{factors}_masked.fna"
    shell:
        "python3 scripts/masking_to_no_factor.py {wildcards.factors} \
            {wildcards.windows} {input} {output}"

rule CGR:
    input:
        "data/genomes/{windows}/{species}_{factors}_masked.fna"
    output:
        "data/following/CGRs/{windows}/{species}_{factors}_done.txt"
    threads:
        99
    shell:
        "python3 ../scripts/windowed_CGR.py {input} {wildcards.windows} \
            {threads} {output} {wildcards.factors}"

rule FCGR:
    input:
        "data/following/CGRs/{windows}/{species}_{factors}_done.txt"
    output:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_FCGRs.txt"
    threads:
        99
    shell:
        "python3 ../scripts/windowed_FCGR.py {input} {wildcards.species} \
            {wildcards.windows} {wildcards.kmer} {threads} {output} \
            {wildcards.factors}"

rule concatenating:
    input:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_FCGRs.txt",
        "files/FCGRs/{windows}_{kmer}/{species}_center_FCGRs.txt"
    output:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_vs_center_FCGRs.txt"
    shell:
        "cat {input} >> {output}"

rule FCGRs_dist:
    input:
        "files/FCGRs/{windows}_{kmer}/{species}_{factors}_vs_center_FCGRs.txt"
    output:
        "files/distances/pearson/{windows}_{kmer}/{species}_{factors}_vs_center_dist_matrix.RData"
    threads:
        99
    shell:
        "Rscript ../scripts/pearson_distance.R {input} {output}"

rule fitting:
    input:
        "files/distances/pearson/{windows}_{kmer}/{species}_dist_matrix.RData"
    output:
        "files/distances/pearson/{windows}_{kmer}/{species}_fit.RData"
    threads:
        99
    shell:
        "Rscript ../scripts/fitting_dist.R {input} {output}"

rule MDS:
    input:
        "files/distances/pearson/{windows}_{kmer}/{species}_fit.RData"
    output:
        "files/results/{windows}_{kmer}_{factors}/{species}_MDS_all_factors.png"
    shell:
        "Rscript ../scripts/cor_dist_factor.R {output} {input} \
            {wildcards.windows} {wildcards.kmer}"
